# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- include_tasks: install-required-packages.yml
- include_tasks: add-solr-user.yml
- include_tasks: install-lucidworks-fusion.yml
- include_role:
    name: configure-solr-nodes
- include_tasks: create-solr-services.yml
- include_tasks: enable-solr-services.yml
- include_tasks: start-solr-services.yml
